import { FC } from "react";
import Head from "next/head";
import NavBar from "./NavBar";
import Footer from "./Footer";

import { Footer_quickSearch } from "../utils/types";

interface Props {
  children: React.ReactNode;
  title: string;
  data: Footer_quickSearch[],
}


const Layout: FC<Props> = ({ children, title, data }) => {
  return (
    <div>
      <Head>
        <title>{title ? title + "Jajiga" : "Jajiga"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <div className="">
          <NavBar />
        </div>
        <main className="min-h-screen">{children}</main>
        <div>
          <footer>
            <Footer data={data} />
          </footer>
        </div>
      </div>
    </div>
  );
};

export default Layout;
