import { FC } from "react";
import Head from "next/head";
import NavBar from "./NavBar";

interface Props {
  children: React.ReactNode;
  title: string;
}

const Layout: FC<Props> = ({ children, title }) => {
  return (
    <div>
      <Head>
        <title>{title ? title + "Jajiga" : "Jajiga"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <div className="">
          <NavBar />
        </div>
        <main className="min-h-screen">{children}</main>
        <div>
          <footer className="flex justify-center items-center h-10 bg-gray-200">
            Footer
          </footer>
        </div>
      </div>
    </div>
  );
};

export default Layout;
